#!/usr/bin/env bash

if [ -z "$VAGRANT_VER" ]; then
	VAGRANT_VER="1.7.4_x86_64"
fi

vagrant__install() {
	if using_apt; then
		basket__pushd ${BASKET__PATH_TEMP}
			basket__wget https://dl.bintray.com/mitchellh/vagrant/vagrant_${VAGRANT_VER}.deb
			with_sudo dpkg -i vagrant_${VAGRANT_VER}.deb
		basket__popd
	elif using_yum; then
		basket__pushd ${BASKET__PATH_TEMP}
			# :TODO: check dependencies
			basket__wget https://dl.bintray.com/mitchellh/vagrant/vagrant_${VAGRANT_VER}.rpm
			with_sudo rpm -Uvh vagrant_${VAGRANT_VER}.rpm
		basket__popd
	else
		await_input "Vagrant installation is currently only available for Debian and Redhat based systems, sorry!"
	fi
}
